name = "WeakDeps"
version = "0.1.0"
uuid = "51376d7c-8773-49f1-a908-35285560668d"

[weakdeps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"

[extensions]
# name of extension to the left
# extension dependencies required to load the extension to the right
# use a list for multiple extension dependencies
WeakDepsCairoMakieExt = "CairoMakie"
